In [2]:
from statsmodels.stats.descriptivestats import sign_test
import pandas as pd
import numpy as np
import json
# plotting
import matplotlib.pyplot as plt
#opening data
import os
import pathlib
import warnings

pd.options.mode.chained_assignment = None
warnings.filterwarnings('ignore')

In [3]:
#open event data
train = pd.DataFrame()
path = pathlib.Path('/home/ganesh/soccermatics/data/wyscout/events_England.json')
with open(path) as f:
    data = json.load(f)
train = pd.concat([train, pd.DataFrame(data)])

path = pathlib.Path('/home/ganesh/soccermatics/data/wyscout/players.json')

#open dataset with players
with open(path) as f:
    players = json.load(f)
player_df = pd.DataFrame(players)

In [ ]:
# take shots only
shots = train.loc[train['subEventName'] == 'Shot']
shots

,eventId,subEventName,tags,playerId,positions,matchId,eventName,teamId,matchPeriod,eventSec,subEventId,id
46,10,Shot,"[{'id': 101}, {'id': 402}, {'id': 201}, {'id':...",25413,"[{'y': 41, 'x': 88}, {'y': 0, 'x': 0}]",2499719,Shot,1609,1H,94.595788,100,177959212
62,10,Shot,"[{'id': 401}, {'id': 201}, {'id': 1211}, {'id'...",26150,"[{'y': 52, 'x': 85}, {'y': 100, 'x': 100}]",2499719,Shot,1631,1H,179.854785,100,177959247
91,10,Shot,"[{'id': 101}, {'id': 403}, {'id': 201}, {'id':...",14763,"[{'y': 52, 'x': 96}, {'y': 100, 'x': 100}]",2499719,Shot,1631,1H,254.745027,100,177959280
128,10,Shot,"[{'id': 401}, {'id': 201}, {'id': 1215}, {'id'...",7868,"[{'y': 33, 'x': 81}, {'y': 0, 'x': 0}]",2499719,Shot,1609,1H,425.824035,100,177959289
249,10,Shot,"[{'id': 402}, {'id': 201}, {'id': 1205}, {'id'...",7868,"[{'y': 30, 'x': 75}, {'y': 0, 'x': 0}]",2499719,Shot,1609,1H,815.462015,100,177959429
...,...,...,...,...,...,...,...,...,...,...,...,...
642945,10,Shot,"[{'id': 401}, {'id': 1212}, {'id': 1802}]",8561,"[{'y': 45, 'x': 72}, {'y': 0, 'x': 0}]",2500098,Shot,1633,2H,1972.969422,100,251596053
643023,10,Shot,"[{'id': 101}, {'id': 402}, {'id': 201}, {'id':...",41174,"[{'y': 33, 'x': 86}, {'y': 0, 'x': 0}]",2500098,Shot,1633,2H,2193.887080,100,251596096
643051,10,Shot,"[{'id': 402}, {'id': 201}, {'id': 1201}, {'id'...",7879,"[{'y': 62, 'x': 88}, {'y': 100, 'x': 100}]",2500098,Shot,1623,2H,2377.197700,100,251596357
643055,10,Shot,"[{'id': 402}, {'id': 201}, {'id': 1206}, {'id'...",145692,"[{'y': 38, 'x': 92}, {'y': 100, 'x': 100}]",2500098,Shot,1623,2H,2381.481625,100,251596359
643149,10,Shot,"[{'id': 403}, {'id': 201}, {'id': 1216}, {'id'...",8005,"[{'y': 50, 'x': 86}, {'y': 0, 'x': 0}]",2500098,Shot,1633,2H,2834.127168,100,251596236

In [ ]:
# get son's shots
son_id = player_df.loc[player_df["shortName"] == "Son Heung-Min"]["wyId"].iloc[0]
son_shots = shots.loc[shots["playerId"] == son_id]
son_shots

,eventId,subEventName,tags,playerId,positions,matchId,eventName,teamId,matchPeriod,eventSec,subEventId,id
44012,10,Shot,"[{'id': 402}, {'id': 1216}, {'id': 1802}]",14911,"[{'y': 25, 'x': 87}, {'y': 0, 'x': 0}]",2499746,Shot,1624,1H,41.025320,100,182699784
76728,10,Shot,"[{'id': 1901}, {'id': 401}, {'id': 201}, {'id'...",14911,"[{'y': 28, 'x': 93}, {'y': 0, 'x': 0}]",2499766,Shot,1624,1H,628.104553,100,187932110
76860,10,Shot,"[{'id': 402}, {'id': 201}, {'id': 1216}, {'id'...",14911,"[{'y': 50, 'x': 79}, {'y': 0, 'x': 0}]",2499766,Shot,1624,1H,1048.499703,100,187932252
77625,10,Shot,"[{'id': 402}, {'id': 201}, {'id': 1201}, {'id'...",14911,"[{'y': 40, 'x': 81}, {'y': 0, 'x': 0}]",2499766,Shot,1624,2H,668.087020,100,187933112
77642,10,Shot,"[{'id': 402}, {'id': 201}, {'id': 1206}, {'id'...",14911,"[{'y': 65, 'x': 96}, {'y': 0, 'x': 0}]",2499766,Shot,1624,2H,731.945802,100,187933131
...,...,...,...,...,...,...,...,...,...,...,...,...
554115,10,Shot,"[{'id': 1901}, {'id': 402}, {'id': 201}, {'id'...",14911,"[{'y': 52, 'x': 89}, {'y': 100, 'x': 100}]",2500046,Shot,1624,1H,1375.758010,100,240758480
573280,10,Shot,"[{'id': 401}, {'id': 2101}, {'id': 1802}]",14911,"[{'y': 74, 'x': 79}, {'y': 0, 'x': 0}]",2500057,Shot,1624,2H,2371.454628,100,242913924
578970,10,Shot,"[{'id': 401}, {'id': 201}, {'id': 1205}, {'id'...",14911,"[{'y': 28, 'x': 91}, {'y': 100, 'x': 100}]",2500061,Shot,1624,1H,1345.409728,100,244031718
579497,10,Shot,"[{'id': 402}, {'id': 201}, {'id': 1202}, {'id'...",14911,"[{'y': 45, 'x': 88}, {'y': 100, 'x': 100}]",2500061,Shot,1624,1H,2935.835299,100,244032276
626591,10,Shot,"[{'id': 402}, {'id': 201}, {'id': 1201}, {'id'...",14911,"[{'y': 26, 'x': 85}, {'y': 100, 'x': 100}]",2500088,Shot,1624,2H,2563.621670,100,249307706

In [ ]:
#left leg shots
lefty_shots = son_shots.loc[son_shots.apply (lambda x:{'id':401} in x.tags, axis = 1)]
#right leg shots
righty_shots = son_shots.loc[son_shots.apply (lambda x:{'id':402} in x.tags, axis = 1)]

#create list with ones for left foot shots and -1 for right foot shots
l = [1] * len(lefty_shots)
l.extend([-1] * len(righty_shots))
len(l)

67

In [17]:
test = sign_test(l, mu0 = 0)
pvalue = test[1]

if pvalue < 0.05:
    print("P-value amounts to", str(pvalue)[:5], "- We reject null hypothesis - Heung-Min Son is not ambidextrous")
else:
    print("P-value amounts to", str(pvalue)[:5], " - We do not reject null hypothesis - Heung-Min Son is ambidextrous")

P-value amounts to 0.142  - We do not reject null hypothesis - Heung-Min Son is ambidextrous